server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # ✅ AUTH SERVICE (Public)
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            # ✅ Admin APIs (Employee-Service)
            - id: admin-employee-service
              uri: http://localhost:8082
              predicates:
                - Path=/admin/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@rateLimiterKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10

            # ✅ EMPLOYEE SERVICE (Protected + Rate Limit)
            - id: employee-service
              uri: http://localhost:8082
              predicates:
                - Path=/employee/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@rateLimiterKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

            # ✅ ATTENDANCE SERVICE (Protected + Rate Limit)
            - id: attendance-service
              uri: http://localhost:8083
              predicates:
                - Path=/attendance/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@rateLimiterKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10

            # ✅ PAYROLL SERVICE (Protected + Strong limit)
            - id: payroll-service
              uri: http://localhost:8087
              predicates:
                - Path=/payroll/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@rateLimiterKeyResolver}"
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 5

            # ✅ WebSocket Routing (Notification service)
            - id: notification-ws
              uri: ws://localhost:8090
              predicates:
                - Path=/ws/**

security:
  jwt:
    secret: ems-secret-key-ems-secret-key-ems-secret-key

cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200,http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
