server:
  port: 8082 # Employee service runs on 8082

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/ems_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none       # schema controlled using schema-mysql.sql
    show-sql: true         # prints SQL to console (debug)
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms

employee:
  cache:
    ttl-seconds: 600 # employee profile cache TTL
