server:
  port: 8087

spring:
  application:
    name: payroll-service

  datasource:
    url: jdbc:mysql://localhost:3306/ems_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

employee-service:
  base-url: http://localhost:8082

attendance-service:
  base-url: http://localhost:8083
